# Generated by Django 5.2.6 on 2026-05-11 16:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendancescan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLunchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Inicio almuerzo')),
                ('end_time', models.TimeField(verbose_name='Fin almuerzo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'ordering': ['project__name', 'weekday', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_source',
            field=models.CharField(choices=[('qr', 'QR'), ('biometric', 'Biométrico'), ('manual', 'Manual')], default='qr', max_length=20, verbose_name='Método ingreso'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_source',
            field=models.CharField(choices=[('qr', 'QR'), ('biometric', 'Biométrico'), ('manual', 'Manual')], default='qr', max_length=20, verbose_name='Método salida'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendancescan',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='attendancescan',
            name='verification_reference',
            field=models.CharField(blank=True, help_text='Referencia del proveedor biométrico o del dispositivo. No guardar datos biométricos crudos.', max_length=120, verbose_name='Referencia verificación'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - Dólar'), ('COP', 'COP - Peso colombiano')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='employee',
            name='document_id',
            field=models.CharField(blank=True, help_text='Opcional. Puede contener letras, números, guiones o puntos.', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El documento solo puede contener letras, números, guiones o puntos.', regex='^[A-Za-z0-9\\-\\.]+$')], verbose_name='Documento / ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - Dólar'), ('COP', 'COP - Peso colombiano')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_currency',
            field=models.CharField(choices=[('USD', 'USD - Dólar'), ('COP', 'COP - Peso colombiano')], default='USD', max_length=3, verbose_name='Moneda del contrato'),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - Dólar'), ('COP', 'COP - Peso colombiano')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='projectincome',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - Dólar'), ('COP', 'COP - Peso colombiano')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='manual_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Override de minutos netos ya revisados.', null=True),
        ),
        migrations.AlterField(
            model_name='attendancescan',
            name='action',
            field=models.CharField(choices=[('in', 'Ingreso'), ('out', 'Salida')], max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancescan',
            name='source',
            field=models.CharField(choices=[('qr', 'QR'), ('biometric', 'Biométrico'), ('manual', 'Manual')], default='qr', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')], verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tarifa por hora'),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ajuste (+/-)'),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tarifa por hora'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.project', verbose_name='Proyecto opcional'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor del contrato'),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='category',
            field=models.CharField(choices=[('materials', 'Materiales'), ('transport', 'Transporte'), ('meals', 'Comida'), ('tools', 'Herramientas'), ('payroll', 'Nómina'), ('other', 'Otros')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='attendancescan',
            index=models.Index(fields=['project', 'server_ts'], name='attendance__project_0b0ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancescan',
            index=models.Index(fields=['source', 'server_ts'], name='attendance__source_ef2528_idx'),
        ),
        migrations.AddField(
            model_name='projectlunchrule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch_rules', to='attendance.project', verbose_name='Proyecto'),
        ),
    ]
